### ISSUE TITLE
Plugin points to wrong data folder in multi-site grav setup 

### ISSUE THREAD

**Issue by kaitlinthachuk** [getgrav/grav-plugin-data-manager#29]
I am using the Grav Multi-site setup such that I have mainsite.com with two sub-sites: mainsite.com/subsite1 and mainsite.com/subsite2. When I log in to the admin panel using mainsite.com/admin I see the data manager pulls the data from user/data, however when I log into any of my sub-site admin panels the data manager still points to the mainsite's data folder rather than using the sub-site's folder using the path user/sites/subsite1/data. I tried to poke around and see if there was an easy way to redirect it but didn't find what I was looking for. Any suggestions on how to fix this would be appreciated!

**Comment by mahagr** [comment]
You need to setup all the file locations manually per multi-site setup. Some sites may want to share the data, some may want their own. Because of that, the multi-site configuration needs to be tuned for every setup -- you need to figure out what you want to share between the sites and what is unique to every/some of them.

There's a streams.yaml which allows you to configure this; I think there are some examples in learn site.

**Comment by kaitlinthachuk** [comment]
Okay, thanks for your quick response.  I did some poking around and managed to fix it myself by redefining some things.
